########################################################################################################################
## db
########################################################################################################################
# https://www.postgresql.jp/document/7.3/programmer/libpq-connect.html

.PHONY: db-up
db-up: $(VARS)
	docker compose up -d mysql
	@echo -n "Waiting boot... "
	@docker compose exec postgres "sh" "-c" "while ! mysqladmin ping -hmysql --silent; do echo -n '.'; sleep 1; done"
	@echo "[OK]"

.PHONY: db-down
db-down:
	docker compose down mysql

.PHONY: db-cli
db-cli:
	docker compose exec mysql mysql "--user=$(MYSQL_USER)" "--password=$(MYSQL_PASS)" "$(MYSQL_NAME)"

.PHONY: db-run
db-run:
	docker compose exec mysql mysql "--user=$(MYSQL_USER)" "--password=$(MYSQL_PASS)" "$(MYSQL_NAME)"

.PHONY: db-dump
db-dump:
	docker compose exec mysql mysqldump "--user=$(MYSQL_USER)" "--password=$(MYSQL_PASS)" "$(MYSQL_NAME)"

.PHONY: db-read
db-read: db-up
	docker compose exec -T mysql mysql "--user=$(MYSQL_USER)" "--password=$(MYSQL_PASS)" "$(MYSQL_NAME)"

.PHONY: db-log
db-log:
	docker compose logs mysql -f --tail 0

## backup / restore

.PHONY: db-backup
db-backup:
	$(MAKE) db-dump > dump.sql

.PHONY: db-restore
db-restore:
	$(MAKE) db-read < dump.sql
