########################################################################################################################
## service
########################################################################################################################

.PHONY: all
all: ps ;

.PHONY: up
up: $(VARS)
	docker compose up -d

.PHONY: down
down:
	docker compose down

.PHONY: reload
reload:
	$(MAKE) down
	$(MAKE) up

.PHONY: restart
restart:
	docker compose restart

.PHONY: build
build:
	docker compose build

.PHONY: pull
pull:
	docker compose pull

.PHONY: log
log:
	docker compose logs -f --tail 0

.PHONY: log-all
log-all:
	docker compose logs --tail all

.PHONY: ps
ps:
	docker compose ps

.PHONY: top
top:
	docker compose top

########################################################################################################################
## Make $(VARS) directory.
########################################################################################################################

$(VARS):
	mkdir -p "$@"
