########################################################################################################################
## service
########################################################################################################################

.PHONY: all
all: ps ;

.PHONY: up
up: vars
	docker compose up -d

.PHONY: down
down:
	docker compose down

.PHONY: reload
reload:
	$(MAKE) down
	$(MAKE) up

.PHONY: restart
restart:
	docker compose restart

.PHONY: build
build:
	docker compose build

.PHONY: pull
pull:
	docker compose pull

.PHONY: log
log:
	docker compose logs -f --tail 0

.PHONY: log-all
log-all:
	docker compose logs --tail all

.PHONY: ps
ps:
	docker compose ps

.PHONY: top
top:
	docker compose top

########################################################################################################################
## Make $(VARS) directory.
########################################################################################################################

# 前提条件は makefile の読み込み時に展開されるので、`up: $(VARS)` と書くと
# include より後ろで VARS を定義しているスタックでは空になり、mkdir が効かない。
# recipe の中なら実行時展開なので、VARS をどこで定義していても効く。
.PHONY: vars
vars:
	$(foreach v,$(VARS),mkdir -p "$(v)" &&) true

$(VARS):
	mkdir -p "$@"
